In [1]:
import numpy as np
list1=[1,2,3,4]
list2=[5,6,7,8]
np.array(list1)+np.array(list2)

array([ 6,  8, 10, 12])

In [6]:
arr2=np.arange(0,10,13)
print(arr2)

[0]


In [7]:
arr2=np.linspace(0,10,13)
print(arr2)

[ 0.          0.83333333  1.66666667  2.5         3.33333333  4.16666667
  5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.        ]


In [16]:
arr=np.arange(20)
re_arr=arr.reshape(4,5)
print(re_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
import numpy as np
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
print(np.sin(4))

-0.7568024953079282


In [8]:
arr1=np.arange(1,5)
arr2=np.arange(6,10)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr2/arr1)
print(1/arr1)
print(arr1**arr2)

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[6.         3.5        2.66666667 2.25      ]
[1.         0.5        0.33333333 0.25      ]
[     1    128   6561 262144]


In [10]:
matrix1=np.arange(25).reshape(5,5)
matrix2=np.arange(25).reshape(5,5)
np.dot(matrix1,matrix2)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [12]:
np.transpose(matrix1)
print(matrix1)
np.dot(matrix1,matrix2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])